In [2]:
import pandas as pd
df = pd.read_csv('gld_price_data.csv.xls')
df

           Date          SPX         GLD        USO      SLV   EUR/USD
0      1/2/2008  1447.160034   84.860001  78.470001  15.1800  1.471692
1      1/3/2008  1447.160034   85.570000  78.370003  15.2850  1.474491
2      1/4/2008  1411.630005   85.129997  77.309998  15.1670  1.475492
3      1/7/2008  1416.180054   84.769997  75.500000  15.0530  1.468299
4      1/8/2008  1390.189941   86.779999  76.059998  15.5900  1.557099
...         ...          ...         ...        ...      ...       ...
2285   5/8/2018  2671.919922  124.589996  14.060000  15.5100  1.186789
2286   5/9/2018  2697.790039  124.330002  14.370000  15.5300  1.184722
2287  5/10/2018  2723.070068  125.180000  14.410000  15.7400  1.191753
2288  5/14/2018  2730.129883  124.489998  14.380000  15.5600  1.193118
2289  5/16/2018  2725.780029  122.543800  14.405800  15.4542  1.182033

[2290 rows x 6 columns]

In [3]:
#understanding the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2290 entries, 0 to 2289
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     2290 non-null   object
 1   SPX      2290 non-null   float64
 2   GLD      2290 non-null   float64
 3   USO      2290 non-null   float64
 4   SLV      2290 non-null   float64
 5   EUR/USD  2290 non-null   float64
dtypes: float64(5), object(1)
memory usage: 107.5+ KB

In [4]:
df.isnull().sum()

Date       0
SPX        0
GLD        0
USO        0
SLV        0
EUR/USD    0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x = df.drop(['Date','GLD'],axis=1)
y = df['GLD']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape
y_train.shape

(1832,)

In [8]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
pred = model.predict(x_test)
pred

array([122.51325689, 127.0907545 , 125.50313349, 104.54764991,
       124.90068634, 116.586858  , 123.04583828, 125.14446632,
       112.05259024, 104.88193814, 101.00127079, 157.04211875,
       137.50447931, 110.49031012, 160.83929478,  88.48009266,
       117.77776928, 118.96072884, 121.53807068, 128.1487556 ,
       118.02290942, 116.08975575, 109.6315024 , 103.05777279,
       111.84096218, 120.86033322, 119.62399827, 112.20020453,
       109.19479998, 119.62171119, 196.11502374,  99.10085802,
       157.19764615, 122.07046494, 113.39777112, 123.34726222,
       132.36268845, 152.08038513, 176.64473496, 145.03588282,
       124.05185863, 121.33549213, 122.74098458, 115.57613444,
       122.35927588, 112.09083408,  93.45476082, 116.93571065,
       126.42056988, 118.08975012, 105.4726357 , 126.56933728,
       105.64602965, 151.78330086, 137.80329213, 117.39236458,
       159.54433502, 126.41884417, 100.17367568, 122.74815137,
       109.79583313,  86.2818531 , 113.37269965, 120.30638659,
        88.36184756, 122.81103534, 119.41725002, 111.29315614,
       153.0445584 ,  96.20637023,  84.31722327, 149.65055559,
       147.3327689 , 105.44296836, 144.71870893, 106.92295995,
       119.87249277, 122.93393893, 115.01857301, 112.69369126,
       129.91178694, 114.53567864,  98.54139796,  98.02750568,
       108.32447375, 114.94636714, 103.51185231, 108.60054619,
       159.15373651, 151.46813704, 103.58255406, 125.91008115,
       111.42592386, 109.48536551, 122.65078699, 105.83328848,
       153.10146226,  81.21864937, 127.0054296 , 108.72288521,
       156.93789277, 108.93634056, 117.13851764, 105.91996373,
       145.16128979,  90.03325028,  89.17695297, 179.77968183,
       119.63219626, 111.72915029, 122.72870139, 163.09711924,
       137.54946942, 126.12892263, 149.23231005, 113.81695843,
       121.30542135, 106.80491957, 119.18680566, 120.92504164,
       131.23744132, 116.74173559,  93.75669055, 114.54064649,
       144.2262939 , 112.44420654, 117.16770097,  96.79047371,
       110.99819105, 114.92062409, 106.1364461 , 155.61618749,
        87.37174272, 121.91045715,  81.22500987, 114.76322811,
       100.34515942, 119.26857118,  82.67526507, 117.92908988,
       112.60526013, 106.98557605,  95.44156974, 140.63919601,
       144.91934973, 179.81999423, 118.15544964, 119.20418792,
       118.87016288,  95.98409756, 164.19204561, 111.70368605,
       114.64984557, 136.97043618, 127.07000455, 122.11602235,
       117.74198566, 111.66054501, 121.94510128,  93.8651258 ,
       106.0737137 , 118.11459409, 181.50752368, 123.87888665,
       117.74470328, 144.00540417, 116.3188271 ,  93.23453977,
       110.96024843, 117.28294565, 116.44904686, 115.25214349,
       103.81973005, 106.02140281, 113.68273878, 123.5453599 ,
       143.0845592 , 111.66550714, 121.6213959 , 164.31714463,
        94.81531056, 115.1927643 , 124.90605405, 122.09155509,
       104.27676324, 120.23732564, 129.35061394, 124.19419395,
       166.33259986, 115.49784802,  97.22481333, 117.05518308,
       123.16010135, 118.53783657, 122.20523967,  94.66240206,
       119.75456425,  96.30139248, 112.34087246, 118.99587063,
       122.67497824, 123.7873014 , 117.45251057, 119.0887711 ,
       123.89500215, 111.27641521, 154.2521629 , 121.15532592,
       119.30749905, 110.53599514, 121.8544917 , 119.08690726,
       101.71911984, 118.36912327, 121.47658473, 162.68539187,
        89.46424347, 139.48710905, 123.35546766,  81.69920121,
       120.25360629,  92.27079368, 153.69216023,  89.38588368,
       147.26489721, 112.26996739, 111.65660342, 111.07879652,
       120.41520267, 155.86555219, 122.52944123, 142.90129837,
       103.32080784, 109.83059086, 130.60345157, 190.87765995,
       126.37823519, 111.76475986, 120.81242636, 150.99760767,
       120.58715785, 123.34348267, 124.38372906, 113.89428451,
       175.679565  , 131.89814985, 122.22753278, 180.99304592,
       115.76693649, 118.93265077, 112.01302166, 149.8003349 ,
       112.46005862, 121.23960778, 119.0190104 , 120.70684734,
       116.73742805,  97.24431634, 104.55142323, 127.64747238,
       126.04854396, 158.26549648, 105.56474993,  91.02153826,
        94.78408462, 146.13892135, 158.44930797, 140.45102212,
        80.45870291, 112.53673874, 116.07095261, 150.62493286,
       127.22382351, 115.08546769, 122.00687162, 152.29148764,
       122.10112   , 120.69206768, 116.93610956, 148.93279748,
       112.84313872,  94.14531207,  79.70488891,  98.61761031,
       117.11252669, 121.91242539, 118.57387263, 122.80743221,
        82.52607836,  95.90361797, 140.35190691, 112.67418057,
       127.67459196, 121.89224551, 109.19454633,  81.67979552,
       110.70338736,  95.85931355, 111.73741784, 152.77218044,
       122.19374988, 113.32941281, 121.87357089, 110.39183818,
       129.10752133,  83.85803082, 155.19740202, 136.43832955,
       156.49514332, 124.49359972,  97.3297167 , 105.52629394,
       122.1172574 , 130.67242053, 126.5572266 ,  95.36070229,
       134.6942144 , 153.47533568,  80.12521938, 114.12288602,
       106.98299591, 116.26094853, 120.31865934, 109.97469715,
       118.77547092, 111.54001657, 123.14310797, 125.3992898 ,
       107.50095592, 157.13739418, 168.7138855 , 109.12754023,
       161.02590312, 109.47615751, 152.7623049 , 122.02895148,
       157.58116197, 139.25523713, 106.47833675, 158.26617953,
       119.12414951,  81.28429944, 115.22337114,  92.32509568,
        94.31073481, 112.78051436, 126.0759017 , 122.20534585,
       158.86943782, 120.07234831,  92.56873772, 139.25721297,
       116.65321875, 104.55342968, 162.3822574 , 122.61613086,
       126.44463982, 115.89991634, 139.19553779, 123.47032933,
       174.10077133, 121.87975884, 120.33159791, 124.00222196,
       156.83639239,  77.85036022, 155.58490381, 159.97410035,
       116.936463  , 110.75892693, 123.19196993, 142.6355607 ,
       162.8469849 , 142.84897551, 124.71428391, 120.36165914,
       162.86183626,  93.55233321, 123.38402696, 119.83827513,
       150.87620441, 145.41622111, 154.77447922, 116.98643814,
        93.43785799, 127.90036537, 103.90627535, 122.95606825,
       123.2152283 , 105.71955569,  97.40014466, 145.50835617,
       100.27834571,  87.31867487, 117.80966769,  92.58204454,
        96.65124069, 115.39405056, 143.92197572, 161.60199703,
       111.47631022, 158.09483693, 114.41357595, 130.56793736,
        91.19238343, 118.95454135,  83.40854416, 116.00966456,
       155.37839748, 143.77361795, 141.01919331, 152.53620774,
        96.78667524, 118.02111391,  96.84232664, 121.78037354,
       118.07696145, 120.60506344, 116.61539754, 121.24481321,
       104.56816667, 160.07040611, 157.40677574, 118.55011052,
       159.31184763,  89.28920017, 158.4976012 , 127.03049802,
       122.3553243 ,  96.78023515, 117.60486742,  87.6788779 ,
       118.90412426, 109.3723111 , 118.97709362, 145.9480029 ,
       148.40954226, 119.27213656, 114.06487922, 118.06301257,
       114.46169379, 121.37832067, 122.30355013, 147.12830151,
       161.35692762, 160.17636413, 102.82012303, 151.8505014 ,
        95.98935898, 141.25223719, 123.41521232,  87.55174804,
       113.64988924, 122.07413592, 161.75342541,  97.9982262 ,
       101.34886277, 145.86292437])

In [11]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 56.165594215005996

In [19]:
#RandomForestRegression since it is regression problem
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train,y_train)
pred1 = model.predict(x_test)

In [21]:
#r2 in regression works as accuracy in classification
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
mae = mean_absolute_error(y_test, pred1)
print(f"Mean Absolute Error: {mae}")
r2 = r2_score(y_test, pred1)
print(f"R-squared: {r2}")
mse = mean_squared_error(y_test, pred1)
print(f"Mean Squared Error: {mse}")

Mean Absolute Error: 1.246459683100437
R-squared: 0.9899387633957437
Mean Squared Error: 5.516574980381914

In [22]:
#Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(x_train,y_train)
pred2 = model.predict(x_test)

In [25]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
mae = mean_absolute_error(y_test, pred2)
print(f"Mean Absolute Error: {mae}")
r2 = r2_score(y_test, pred1)
print(f"R-squared: {r2}")
mse = mean_squared_error(y_test, pred1)
print(f"Mean Squared Error: {mse}")

Mean Absolute Error: 1.3812226375545846
R-squared: 0.9899387633957437
Mean Squared Error: 5.516574980381914